language: ruby
before_install: if [[ "$TRAVIS_RUBY_VERSION" = "1.9.3" ]]; then gem install bundler --version="1.3.5"; else gem install bundler; fi
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
env:
  - RAILS_VERSION="~> 3.2.0"
  - RAILS_VERSION="~> 4.0.0"
  - RAILS_VERSION="~> 4.1.0.beta1"
